src/frontend/OpenTelemetry.Example.Dotnet.Frontend/Pages/EventCatalog/Detail.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OpenTelemetry.Example.Dotnet.Frontend.Extensions;
using OpenTelemetry.Example.Dotnet.Frontend.Models;
using OpenTelemetry.Example.Dotnet.Frontend.Models.Api;
using OpenTelemetry.Example.Dotnet.Frontend.Services.EventCatalog;
using OpenTelemetry.Example.Dotnet.Frontend.Services.ShoppingBasket;

namespace OpenTelemetry.Example.Dotnet.Frontend.Pages.EventCatalog;

public class Detail : PageModel
{
    public Event Event { get; set; }

    [BindProperty]
    public BasketLineForCreation BasketLineForCreation { get; set; }
    
    private IEventCatalogService _eventCatalogService;
    private IShoppingBasketService _basketService;
    private Settings _settings;
    
    public Detail(IEventCatalogService eventCatalogService , IShoppingBasketService basketService , Settings settings)
    { 
        _eventCatalogService = eventCatalogService;
        _basketService = basketService;
        _settings = settings;
    }

    public async Task OnGet(Guid eventId)
    {
        Event = await _eventCatalogService.GetEvent(eventId);
    }

    public async Task<IActionResult> OnPostAddToBasket()
    {
        if (ModelState.IsValid)
        {
            var basketId = Request.Cookies.GetCurrentBasketId(_settings);
            var newLine = await _basketService.AddToBasket(basketId, BasketLineForCreation);
            Response.Cookies.Append(_settings.BasketIdCookieName, newLine.BasketId.ToString());
            return RedirectToPage("/ShoppingBasket/List");
        }
        
        
        //Event = await _eventCatalogService.GetEvent(BasketLineForCreation.EventId);
        return Page();
    }
}

src/frontend/OpenTelemetry.Example.Dotnet.Frontend/Pages/EventCatalog/List.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using OpenTelemetry.Example.Dotnet.Frontend.Extensions;
using OpenTelemetry.Example.Dotnet.Frontend.Models;
using OpenTelemetry.Example.Dotnet.Frontend.Models.Api;
using OpenTelemetry.Example.Dotnet.Frontend.Models.View;
using OpenTelemetry.Example.Dotnet.Frontend.Services.EventCatalog;
using OpenTelemetry.Example.Dotnet.Frontend.Services.ShoppingBasket;

namespace OpenTelemetry.Example.Dotnet.Frontend.Pages.EventCatalog;

public class List : PageModel
{
    //public IEnumerable<Event> Events { get; private set; }
    public EventListModel ListModel { get; set; }
    private IEventCatalogService _eventCatalogService;
    private IShoppingBasketService _shoppingBasketService;
    private Settings _settings;
    private ILogger<List> _logger;
    public List(IEventCatalogService eventCatalogService,IShoppingBasketService shoppingBasketService,Settings settings,ILogger<List> logger)
    {
        
        _eventCatalogService = eventCatalogService;
        _shoppingBasketService = shoppingBasketService;
        _settings = settings;
        _logger = logger;
    }
    public async Task OnGet()
    {
        var currentBasketId = Request.Cookies.GetCurrentBasketId(_settings);
        var getBasket = _shoppingBasketService.GetBasket(currentBasketId);
        var getEvents = _eventCatalogService.GetAll();
        var errorMessage = string.Empty;
        try
        {
            await Task.WhenAll(new Task[] { getBasket, getEvents });
        } catch(Exception ex)
        {
            // could be due an mDNS failure to talk to event catalog service when running locally
            // https://github.com/dapr/dapr/issues/3256
            _logger.LogError(ex, "Failure fetching data for event catalog page");
            errorMessage = $"Unable to load data: {ex.Message}";
        }
        var numberOfItems = getBasket.IsCompletedSuccessfully ? getBasket.Result.NumberOfItems : 0;
        var events = getEvents.IsCompletedSuccessfully ? getEvents.Result : Array.Empty<Event>();
        //_logger.LogInformation( JsonSerializer.Serialize(events));

        ListModel =
            new EventListModel
            {
                Events = events,
                NumberOfItems = numberOfItems,
                ErrorMessage = errorMessage
            };

    }
}

src/frontend/OpenTelemetry.Example.Dotnet.Frontend/Pages/ShoppingBasket/List.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OpenTelemetry.Example.Dotnet.Frontend.Extensions;
using OpenTelemetry.Example.Dotnet.Frontend.Models;
using OpenTelemetry.Example.Dotnet.Frontend.Models.Api;
using OpenTelemetry.Example.Dotnet.Frontend.Models.View;
using OpenTelemetry.Example.Dotnet.Frontend.Services.ShoppingBasket;

namespace OpenTelemetry.Example.Dotnet.Frontend.Pages.ShoppingBasket;

public class List : PageModel
{
    [BindProperty]
    public BasketLineForUpdate BasketLineUpdate { get; set; }
    
    public IEnumerable<BasketLineViewModel> BasketLineViewModels { get; set; }
    private IShoppingBasketService _basketService;
    
    
    private Settings _settings;
    public List(IShoppingBasketService basketService,Settings settings)
    {
        _basketService = basketService;
        _settings = settings;
    }
    
    
    

    public async Task OnGet()
    {
        var basketLines = await _basketService.GetLinesForBasket(Request.Cookies.GetCurrentBasketId(_settings));
        BasketLineViewModels = basketLines.Select(bl => new BasketLineViewModel
            {
                LineId = bl.BasketLineId,
                EventId = bl.EventId,
                EventName = bl.Event.Name,
                Date = bl.Event.Date,
                Price = bl.Price,
                Quantity = bl.TicketAmount
            }
        );
    }

    public async Task OnPostUpdateLine()
    {
        if (ModelState.IsValid)
        {
            var basketId = Request.Cookies.GetCurrentBasketId(_settings);
            await _basketService.UpdateLine(basketId, BasketLineUpdate);
        }
        OnGet();
    }
    public async  Task OnGetRemoveLine(Guid lineId)
    {
        var basketId = Request.Cookies.GetCurrentBasketId(_settings);
        await _basketService.RemoveLine(basketId, lineId);
        OnGet();
    }
    


}

src/frontend/OpenTelemetry.Example.Dotnet.Frontend/Pages/EventCatalog/Detail.cshtml
@page
@model OpenTelemetry.Example.Dotnet.Frontend.Pages.EventCatalog.Detail
<div class="row mt-5">
    <div class="col-md-4">
        <img src="@Model.Event!.ImageUrl" class="detailImage" alt="Artist pic" />
    </div>
    <div class="col-md-6 ml-1">
        <div class="row">
            <div class="columnHeader">SHOW</div>
        </div>
        <div class="row mt-2 bold">
            <h1>@Model.Event!.Name</h1>
        </div>
        <div class="row mt-2">
            <h3>@Model.Event!.Artist</h3>
        </div>
        <div class="row mt-3 mt-4 bold">
            <h3>@Model.Event!.Date.ToShortDateString()</h3>
        </div>
        <div class="row mt-4">
            @Model.Event!.Description
        </div>
        <div class="row mt-5">
            <h3><span class="bold">$@Model.Event!.Price</span></h3><span class="mt-1">&nbsp;&nbsp;&nbsp; PER TICKET</span>
        </div>
    </div>
</div>
<div class="row mt-5">
    <div class="col">
        <hr />
    </div>
</div>
<div class="row mt-4">
    <div class="col offset-4">
        <form class="form" method="post" asp-page-handler="AddToBasket">
            <div class="row">
                <label class="columnHeader mt-2">QUANTITY:</label>
               
                <select asp-for="@Model.BasketLineForCreation.TicketAmount" class="ml-5 w-25">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
                <input  type="hidden" asp-for="@Model.BasketLineForCreation.EventId" value="@Model.Event.EventId">
                <input  type="hidden" asp-for="@Model.BasketLineForCreation.Price" value="@Model.Event.Price"/> 
                
                <button type="submit" class="btn btn-primary ml-4 w-50">PLACE ORDER</button>
            </div>
        </form>
    </div>
</div>

src/frontend/OpenTelemetry.Example.Dotnet.Frontend/Pages/EventCatalog/List.cshtml
@page
@model OpenTelemetry.Example.Dotnet.Frontend.Pages.EventCatalog.List

<div class="row">
    @if (Model is null || Model.ListModel is null || Model.ListModel.Events is null)
    {
        <text>No events were found.</text>
    }
    else
    {
        <table class="table">
            <thead>
            <tr class="columnHeader">
                <th></th>
                <th>DATE</th>
                <th>NAME</th>
                <th>ARTIST</th>
                <th>PRICE</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            @foreach (var ev in Model.ListModel.Events)
            {
                <tr>
                    <td>
                        <img class="artistPic" src="@ev!.ImageUrl" alt="Artist pic"/>
                    </td>
                    <td>
                        @ev.Date.ToShortDateString()
                    </td>
                    <td>
                        @ev.Name
                    </td>
                    <td>
                        @ev.Artist
                    </td>
                    <td class="bold big">
                        $@ev.Price
                    </td>
                    <td>
                        <a class="btn-primary" type="button" asp-page="/EventCatalog/Detail" asp-route-eventId="@ev.EventId">PURCHASE DETAILS</a>
                    </td>
                </tr>
            }

            </tbody>
        </table>
    }
</div>