src/frontend/OpenTelemetry.Example.Dotnet.Frontend/Pages/EventCatalog/List.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using OpenTelemetry.Example.Dotnet.Frontend.Extensions;
using OpenTelemetry.Example.Dotnet.Frontend.Models;
using OpenTelemetry.Example.Dotnet.Frontend.Models.Api;
using OpenTelemetry.Example.Dotnet.Frontend.Models.View;
using OpenTelemetry.Example.Dotnet.Frontend.Services.EventCatalog;
using OpenTelemetry.Example.Dotnet.Frontend.Services.ShoppingBasket;

namespace OpenTelemetry.Example.Dotnet.Frontend.Pages.EventCatalog;

public class List : PageModel
{
    //public IEnumerable<Event> Events { get; private set; }
    public EventListModel ListModel { get; set; }
    private IEventCatalogService _eventCatalogService;
    private IShoppingBasketService _shoppingBasketService;
    private Settings _settings;
    private ILogger<List> _logger;
    public List(IEventCatalogService eventCatalogService,IShoppingBasketService shoppingBasketService,Settings settings,ILogger<List> logger)
    {
        
        _eventCatalogService = eventCatalogService;
        _shoppingBasketService = shoppingBasketService;
        _settings = settings;
        _logger = logger;
    }
    public async Task OnGet()
    {
        var currentBasketId = Request.Cookies.GetCurrentBasketId(_settings);
        var getBasket = _shoppingBasketService.GetBasket(currentBasketId);
        var getEvents = _eventCatalogService.GetAll();
        var errorMessage = string.Empty;
        try
        {
            await Task.WhenAll(new Task[] { getBasket, getEvents });
        } catch(Exception ex)
        {
            // could be due an mDNS failure to talk to event catalog service when running locally
            // https://github.com/dapr/dapr/issues/3256
            _logger.LogError(ex, "Failure fetching data for event catalog page");
            errorMessage = $"Unable to load data: {ex.Message}";
        }
        var numberOfItems = getBasket.IsCompletedSuccessfully ? getBasket.Result.NumberOfItems : 0;
        var events = getEvents.IsCompletedSuccessfully ? getEvents.Result : Array.Empty<Event>();
        //_logger.LogInformation( JsonSerializer.Serialize(events));

        ListModel =
            new EventListModel
            {
                Events = events,
                NumberOfItems = numberOfItems,
                ErrorMessage = errorMessage
            };

    }
}

src/frontend/OpenTelemetry.Example.Dotnet.Frontend/Pages/ShoppingBasket/List.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OpenTelemetry.Example.Dotnet.Frontend.Extensions;
using OpenTelemetry.Example.Dotnet.Frontend.Models;
using OpenTelemetry.Example.Dotnet.Frontend.Models.Api;
using OpenTelemetry.Example.Dotnet.Frontend.Models.View;
using OpenTelemetry.Example.Dotnet.Frontend.Services.ShoppingBasket;

namespace OpenTelemetry.Example.Dotnet.Frontend.Pages.ShoppingBasket;

public class List : PageModel
{
    [BindProperty]
    public BasketLineForUpdate BasketLineUpdate { get; set; }
    
    public IEnumerable<BasketLineViewModel> BasketLineViewModels { get; set; }
    private IShoppingBasketService _basketService;
    
    
    private Settings _settings;
    public List(IShoppingBasketService basketService,Settings settings)
    {
        _basketService = basketService;
        _settings = settings;
    }
    
    
    

    public async Task OnGet()
    {
        var basketLines = await _basketService.GetLinesForBasket(Request.Cookies.GetCurrentBasketId(_settings));
        BasketLineViewModels = basketLines.Select(bl => new BasketLineViewModel
            {
                LineId = bl.BasketLineId,
                EventId = bl.EventId,
                EventName = bl.Event.Name,
                Date = bl.Event.Date,
                Price = bl.Price,
                Quantity = bl.TicketAmount
            }
        );
    }

    public async Task OnPostUpdateLine()
    {
        if (ModelState.IsValid)
        {
            var basketId = Request.Cookies.GetCurrentBasketId(_settings);
            await _basketService.UpdateLine(basketId, BasketLineUpdate);
        }
        OnGet();
    }
    public async  Task OnGetRemoveLine(Guid lineId)
    {
        var basketId = Request.Cookies.GetCurrentBasketId(_settings);
        await _basketService.RemoveLine(basketId, lineId);
        OnGet();
    }
    


}

src/frontend/OpenTelemetry.Example.Dotnet.Frontend/Pages/ShoppingBasket/List.cshtml
@page
@using OpenTelemetry.Example.Dotnet.Frontend.Models.View
@model OpenTelemetry.Example.Dotnet.Frontend.Pages.ShoppingBasket.List

<table class="table">
    <thead>
    <tr class="columnHeader">
        <th>EVENT NAME</th>
        <th>DATE</th>
        <th>PRICE PER TICKET</th>
        <th>QUANTITY</th>
        <th>TOTAL</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (BasketLineViewModel line in Model!.BasketLineViewModels)
    {
        <tr>
            <td>@line.EventName</td>
            <td>@line.Date.DateTime.ToShortDateString()</td>
            <td class="bold">$@line.Price</td>
            <td>
                <form method="post" asp-page-handler="UpdateLine">
                    <input type="hidden" asp-for="@Model.BasketLineUpdate.LineId" value="@line.LineId" />
                    <select class="w-25" asp-for="@Model.BasketLineUpdate.TicketAmount">
                        @if (line.Quantity == 1)
                        {
                            <option selected="selected" value="1">1</option>
                        }
                        else
                        {
                            <option value="1">1</option>
                        }

                        @if (line.Quantity == 2)
                        {
                            <option selected="selected" value="2">2</option>
                        }
                        else
                        {
                            <option value="2">2</option>
                        }

                        @if (line.Quantity == 3)
                        {
                            <option selected="selected" value="3">3</option>
                        }
                        else
                        {
                            <option value="3">3</option>
                        }
                        @if (line.Quantity == 4)
                        {
                            <option selected="selected" value="4">4</option>
                        }
                        else
                        {
                            <option value="4">4</option>
                        }
                        @if (line.Quantity == 5)
                        {
                            <option selected="selected" value="5">5</option>
                        }
                        else
                        {
                            <option value="5">5</option>
                        }
                        </select>
                    <button type="submit" class="filterButton">Update</button>
                </form>
            </td>
            <td class="bold big">$@(line.Price * line.Quantity) </td>
            <td>
                <a asp-page-handler="RemoveLine" asp-route-lineId="@line.LineId">Remove</a>
            </td>
        </tr>
    }
        <tr>
            <td colspan="4">
                <a asp-page="/EventCatalog/List"> Back to event catalog</a>
            </td>
            <td class="bold big">$@Model.BasketLineViewModels!.Sum(bl => bl.Price * bl.Quantity)</td>
        </tr>
        
    </tbody>
</table>
@if (Model!.BasketLineViewModels.Any())
{
    <a class="nav-link text-dark" asp-area="" asp-page="/Checkout/New">CHECKOUT</a>
}